name: Push to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy file to EC2
        run: scp -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no path/to/your/file ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/path/on/ec2/

      - name: SSH into EC2 and run commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Amazon Linux 2 commands
            sudo yum -y update
            sudo yum -y install httpd
            sudo systemctl start httpd
            sudo systemctl enable httpd

            # Additional commands if needed
